//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoBrokeIt.UI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoBrokeIt.UI.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build definitions.
        /// </summary>
        internal static string BuildDefinitions {
            get {
                return ResourceManager.GetString("BuildDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        internal static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ddd dd, MMM yyyy &apos;at&apos; HH:mm}.
        /// </summary>
        internal static string DateAndTimeFormat {
            get {
                return ResourceManager.GetString("DateAndTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no build definitions for this project.
        /// </summary>
        internal static string NoBuildDefinitions {
            get {
                return ResourceManager.GetString("NoBuildDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description provided.
        /// </summary>
        internal static string NoDescProvided {
            get {
                return ResourceManager.GetString("NoDescProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Who broke it?.
        /// </summary>
        internal static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to.
        /// </summary>
        internal static string SettingsAcknowledgements {
            get {
                return ResourceManager.GetString("SettingsAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug?.
        /// </summary>
        internal static string SettingsBug {
            get {
                return ResourceManager.GetString("SettingsBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change token.
        /// </summary>
        internal static string SettingsChangeToken {
            get {
                return ResourceManager.GetString("SettingsChangeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from this instance.
        /// </summary>
        internal static string SettingsDisconnect {
            get {
                return ResourceManager.GetString("SettingsDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to disconnect from this instance of Visual Studio Team Services?.
        /// </summary>
        internal static string SettingsDisconnectConfirmationMessage {
            get {
                return ResourceManager.GetString("SettingsDisconnectConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an idea for this app?.
        /// </summary>
        internal static string SettingsIdea {
            get {
                return ResourceManager.GetString("SettingsIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current instance.
        /// </summary>
        internal static string SettingsInstance {
            get {
                return ResourceManager.GetString("SettingsInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab the source code.
        /// </summary>
        internal static string SettingsSourceCode {
            get {
                return ResourceManager.GetString("SettingsSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set token.
        /// </summary>
        internal static string SetToken {
            get {
                return ResourceManager.GetString("SetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View commits.
        /// </summary>
        internal static string ViewCommits {
            get {
                return ResourceManager.GetString("ViewCommits", resourceCulture);
            }
        }
    }
}
