// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WhoBrokeIt.UI.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhoBrokeIt.UI.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        internal static string BuildDefinitions {
            get {
                return ResourceManager.GetString("BuildDefinitions", resourceCulture);
            }
        }
        
        internal static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string DateAndTimeFormat {
            get {
                return ResourceManager.GetString("DateAndTimeFormat", resourceCulture);
            }
        }
        
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        internal static string NoBuildDefinitions {
            get {
                return ResourceManager.GetString("NoBuildDefinitions", resourceCulture);
            }
        }
        
        internal static string NoDescProvided {
            get {
                return ResourceManager.GetString("NoDescProvided", resourceCulture);
            }
        }
        
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        internal static string SettingsAcknowledgements {
            get {
                return ResourceManager.GetString("SettingsAcknowledgements", resourceCulture);
            }
        }
        
        internal static string SettingsBug {
            get {
                return ResourceManager.GetString("SettingsBug", resourceCulture);
            }
        }
        
        internal static string SettingsChangeToken {
            get {
                return ResourceManager.GetString("SettingsChangeToken", resourceCulture);
            }
        }
        
        internal static string SettingsDisconnect {
            get {
                return ResourceManager.GetString("SettingsDisconnect", resourceCulture);
            }
        }
        
        internal static string SettingsIdea {
            get {
                return ResourceManager.GetString("SettingsIdea", resourceCulture);
            }
        }
        
        internal static string SettingsSourceCode {
            get {
                return ResourceManager.GetString("SettingsSourceCode", resourceCulture);
            }
        }
        
        internal static string SetToken {
            get {
                return ResourceManager.GetString("SetToken", resourceCulture);
            }
        }
        
        internal static string ViewCommits {
            get {
                return ResourceManager.GetString("ViewCommits", resourceCulture);
            }
        }
        
        internal static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        internal static string SettingsInstance {
            get {
                return ResourceManager.GetString("SettingsInstance", resourceCulture);
            }
        }
        
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        internal static string SettingsDisconnectConfirmationMessage {
            get {
                return ResourceManager.GetString("SettingsDisconnectConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        internal static string ThanksText {
            get {
                return ResourceManager.GetString("ThanksText", resourceCulture);
            }
        }
    }
}
